# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '慢偶因素Main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from .乳化液.controller.LiquidInterfaceMain import LiquidInterfaceMain
from .轧辊.controller.RollingInterfaceMain import RollingInterfaceMain
from .停机.controller.stopInterface import StopInterface
from .班组.controller.ClassInterface import MainWindow as ClassInterface
from .压下率.controller.ReductionInterface import ReductionInterface
from .热轧来料.controller.HotRollingInterface import HotRollingInterface


class Ui_AccidentalFactor(object):
    def setupUi(self, AccidentalFactor):
        AccidentalFactor.setObjectName("AccidentalFactor")
        AccidentalFactor.resize(1600, 800)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/慢偶因素.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        AccidentalFactor.setWindowIcon(icon)
        self.horizontalLayout = QtWidgets.QHBoxLayout(AccidentalFactor)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.NavigationBar = NavigationBar(AccidentalFactor)
        self.NavigationBar.setObjectName("NavigationBar")
        self.horizontalLayout.addWidget(self.NavigationBar)
        self.stackedWidget = QtWidgets.QStackedWidget(AccidentalFactor)
        self.stackedWidget.setObjectName("stackedWidget")
        self.LiquidPage = LiquidInterfaceMain()
        self.LiquidPage.setObjectName("LiquidPage")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.LiquidPage)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.stackedWidget.addWidget(self.LiquidPage)
        self.ClassPage = ClassInterface()
        self.ClassPage.setObjectName("ClassPage")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.ClassPage)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.stackedWidget.addWidget(self.ClassPage)
        self.ReductionPage = ReductionInterface()
        self.ReductionPage.setObjectName("ReductionPage")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.ReductionPage)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.stackedWidget.addWidget(self.ReductionPage)
        self.StopPage = StopInterface()
        self.StopPage.setObjectName("StopPage")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.StopPage)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.stackedWidget.addWidget(self.StopPage)
        self.MaterialPage = HotRollingInterface()
        self.MaterialPage.setObjectName("MaterialPage")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.MaterialPage)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.stackedWidget.addWidget(self.MaterialPage)
        self.RollingPage = RollingInterfaceMain()
        self.RollingPage.setObjectName("RollingPage")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.RollingPage)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.stackedWidget.addWidget(self.RollingPage)
        self.horizontalLayout.addWidget(self.stackedWidget)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 20)

        self.retranslateUi(AccidentalFactor)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(AccidentalFactor)

    def retranslateUi(self, AccidentalFactor):
        _translate = QtCore.QCoreApplication.translate
        AccidentalFactor.setWindowTitle(_translate("AccidentalFactor", "慢偶因素板形干扰评估"))


from qfluentwidgets import NavigationBar
from qtResource import resource_rc
