# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'accidental_interference_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from accidental_interference.emulsion.controller.LiquidInterfaceMain import LiquidInterfaceMain
from accidental_interference.roller.controller.RollingInterfaceMain import RollingInterfaceMain
from accidental_interference.shutdown.controller.stopInterface import StopInterface
from accidental_interference.class_group.controller.ClassInterface import MainWindow as ClassInterface
from accidental_interference.compression_rate.controller.ReductionInterface import ReductionInterface
from accidental_interference.hot_rolling_incoming.controller.HotRollingInterface import HotRollingInterface


class Ui_AccidentalFactor(object):
    def setupUi(self, AccidentalFactor):
        AccidentalFactor.setObjectName("AccidentalFactor")
        AccidentalFactor.resize(1300, 800)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/慢偶因素.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        AccidentalFactor.setWindowIcon(icon)
        self.horizontalLayout = QtWidgets.QHBoxLayout(AccidentalFactor)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.NavigationBar = NavigationBar(AccidentalFactor)
        self.NavigationBar.setObjectName("NavigationBar")
        self.horizontalLayout.addWidget(self.NavigationBar)
        self.stackedWidget = QtWidgets.QStackedWidget(AccidentalFactor)
        self.stackedWidget.setObjectName("stackedWidget")
        self.LiquidPage = LiquidInterfaceMain()
        self.LiquidPage.setObjectName("LiquidPage")
        self.stackedWidget.addWidget(self.LiquidPage)
        self.ClassPage = ClassInterface()
        self.ClassPage.setObjectName("ClassPage")
        self.stackedWidget.addWidget(self.ClassPage)
        self.ReductionPage = ReductionInterface()
        self.ReductionPage.setObjectName("ReductionPage")
        self.stackedWidget.addWidget(self.ReductionPage)
        self.StopPage = StopInterface()
        self.StopPage.setObjectName("StopPage")
        self.stackedWidget.addWidget(self.StopPage)
        self.MaterialPage = HotRollingInterface()
        self.MaterialPage.setObjectName("MaterialPage")
        self.stackedWidget.addWidget(self.MaterialPage)
        self.RollingPage = RollingInterfaceMain()
        self.RollingPage.setObjectName("RollingPage")
        self.stackedWidget.addWidget(self.RollingPage)
        self.horizontalLayout.addWidget(self.stackedWidget)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 20)

        self.retranslateUi(AccidentalFactor)
        self.stackedWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(AccidentalFactor)

    def retranslateUi(self, AccidentalFactor):
        _translate = QtCore.QCoreApplication.translate
        AccidentalFactor.setWindowTitle(_translate("AccidentalFactor", "慢偶因素板形干扰评估"))


from qfluentwidgets import NavigationBar
