# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '选择轧辊类型警告界面.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_warningDialog(object):
    def setupUi(self, warningDialog):
        warningDialog.setObjectName("warningDialog")
        warningDialog.resize(500, 300)
        warningDialog.setMaximumSize(QtCore.QSize(500, 300))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/警告.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        warningDialog.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(warningDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.CardWidget = CardWidget(warningDialog)
        self.CardWidget.setObjectName("CardWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.CardWidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.SubtitleLabel = SubtitleLabel(self.CardWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SubtitleLabel.sizePolicy().hasHeightForWidth())
        self.SubtitleLabel.setSizePolicy(sizePolicy)
        self.SubtitleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.SubtitleLabel.setWordWrap(True)
        self.SubtitleLabel.setObjectName("SubtitleLabel")
        self.gridLayout_2.addWidget(self.SubtitleLabel, 0, 0, 1, 2)
        self.PrimaryPushButton = PrimaryPushButton(self.CardWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PrimaryPushButton.sizePolicy().hasHeightForWidth())
        self.PrimaryPushButton.setSizePolicy(sizePolicy)
        self.PrimaryPushButton.setObjectName("PrimaryPushButton")
        self.gridLayout_2.addWidget(self.PrimaryPushButton, 1, 0, 1, 1)
        self.PrimaryPushButton_2 = PrimaryPushButton(self.CardWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PrimaryPushButton_2.sizePolicy().hasHeightForWidth())
        self.PrimaryPushButton_2.setSizePolicy(sizePolicy)
        self.PrimaryPushButton_2.setObjectName("PrimaryPushButton_2")
        self.gridLayout_2.addWidget(self.PrimaryPushButton_2, 1, 1, 1, 1)
        self.gridLayout.addWidget(self.CardWidget, 0, 0, 1, 1)

        self.retranslateUi(warningDialog)
        QtCore.QMetaObject.connectSlotsByName(warningDialog)

    def retranslateUi(self, warningDialog):
        _translate = QtCore.QCoreApplication.translate
        warningDialog.setWindowTitle(_translate("warningDialog", "提示"))
        self.SubtitleLabel.setText(_translate("warningDialog", "请选择轧辊类型，返回主界面请单击“返回”。"))
        self.PrimaryPushButton.setText(_translate("warningDialog", "确定"))
        self.PrimaryPushButton_2.setText(_translate("warningDialog", "返回"))
from qfluentwidgets import CardWidget, PrimaryPushButton, SubtitleLabel
from qtResource import resource_rc
