# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '板形质量评价Main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from .一卷数据分析.一卷数据分析 import FullLengthQuality
from .全年数据分析.全年数据分析 import PerYearAnalysis

class Ui_banxingzhiliang(object):
    def setupUi(self, banxingzhiliang):
        banxingzhiliang.setObjectName("banxingzhiliang")
        banxingzhiliang.resize(1300, 1200)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/help.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        banxingzhiliang.setWindowIcon(icon)
        self.horizontalLayout = QtWidgets.QHBoxLayout(banxingzhiliang)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.NavigationBar = NavigationBar(banxingzhiliang)
        self.NavigationBar.setObjectName("NavigationBar")
        self.horizontalLayout.addWidget(self.NavigationBar)
        self.stackedWidget = QtWidgets.QStackedWidget(banxingzhiliang)
        self.stackedWidget.setObjectName("stackedWidget")
        self.fullLengthQualityPage = FullLengthQuality()
        self.fullLengthQualityPage.setObjectName("fullLengthQualityPage")
        # self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.fullLengthQualityPage)
        # self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.stackedWidget.addWidget(self.fullLengthQualityPage)
        self.annualQualityPage = PerYearAnalysis()
        self.annualQualityPage.setObjectName("annualQualityPage")
        self.stackedWidget.addWidget(self.annualQualityPage)
        self.horizontalLayout.addWidget(self.stackedWidget)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 20)

        self.retranslateUi(banxingzhiliang)
        QtCore.QMetaObject.connectSlotsByName(banxingzhiliang)

    def retranslateUi(self, banxingzhiliang):
        _translate = QtCore.QCoreApplication.translate
        banxingzhiliang.setWindowTitle(_translate("banxingzhiliang", "板形质量评价"))
from qfluentwidgets import NavigationBar
from qtResource import resource_rc
