# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '特定时间段IU均值.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SpecialNumIU(object):
    def setupUi(self, SpecialNumIU):
        SpecialNumIU.setObjectName("SpecialNumIU")
        SpecialNumIU.resize(1164, 650)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/预览.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        SpecialNumIU.setWindowIcon(icon)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(SpecialNumIU)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.CardWidget_2 = CardWidget(SpecialNumIU)
        self.CardWidget_2.setObjectName("CardWidget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.CardWidget_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.CaptionLabel = CaptionLabel(self.CardWidget_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.CaptionLabel.setFont(font)
        self.CaptionLabel.setObjectName("CaptionLabel")
        self.gridLayout.addWidget(self.CaptionLabel, 0, 0, 1, 1)
        self.CalendarPicker = CalendarPicker(self.CardWidget_2)
        self.CalendarPicker.setObjectName("CalendarPicker")
        self.gridLayout.addWidget(self.CalendarPicker, 0, 1, 1, 1)
        self.TimeEdit = TimeEdit(self.CardWidget_2)
        self.TimeEdit.setObjectName("TimeEdit")
        self.gridLayout.addWidget(self.TimeEdit, 0, 2, 1, 1)
        self.CaptionLabel_2 = CaptionLabel(self.CardWidget_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.CaptionLabel_2.setFont(font)
        self.CaptionLabel_2.setObjectName("CaptionLabel_2")
        self.gridLayout.addWidget(self.CaptionLabel_2, 1, 0, 1, 1)
        self.CalendarPicker_2 = CalendarPicker(self.CardWidget_2)
        self.CalendarPicker_2.setObjectName("CalendarPicker_2")
        self.gridLayout.addWidget(self.CalendarPicker_2, 1, 1, 1, 1)
        self.TimeEdit_2 = TimeEdit(self.CardWidget_2)
        self.TimeEdit_2.setObjectName("TimeEdit_2")
        self.gridLayout.addWidget(self.TimeEdit_2, 1, 2, 1, 1)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setColumnStretch(1, 2)
        self.gridLayout.setColumnStretch(2, 2)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.PrimaryPushButton = PrimaryPushButton(self.CardWidget_2)
        self.PrimaryPushButton.setObjectName("PrimaryPushButton")
        self.horizontalLayout.addWidget(self.PrimaryPushButton)
        self.horizontalLayout.setStretch(0, 3)
        self.horizontalLayout.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayoutRight = QtWidgets.QGridLayout()
        self.gridLayoutRight.setObjectName("gridLayoutRight")
        self.graphicsView_2 = QtWidgets.QGraphicsView(self.CardWidget_2)
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.gridLayoutRight.addWidget(self.graphicsView_2, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayoutRight)
        self.horizontalLayout_2.addWidget(self.CardWidget_2)

        self.retranslateUi(SpecialNumIU)
        QtCore.QMetaObject.connectSlotsByName(SpecialNumIU)

    def retranslateUi(self, SpecialNumIU):
        _translate = QtCore.QCoreApplication.translate
        SpecialNumIU.setWindowTitle(_translate("SpecialNumIU", "特定时间段IU均值"))
        self.CaptionLabel.setText(_translate("SpecialNumIU", "开始时间"))
        self.CaptionLabel_2.setText(_translate("SpecialNumIU", "截止时间"))
        self.PrimaryPushButton.setText(_translate("SpecialNumIU", "显示图像"))
from qfluentwidgets import CalendarPicker, CaptionLabel, CardWidget, PrimaryPushButton, TimeEdit
from qtResource import resource_rc
