# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rollerDesign.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RollerDesign(object):
    def setupUi(self, RollerDesign):
        RollerDesign.setObjectName("RollerDesign")
        RollerDesign.resize(669, 386)
        self.verticalLayout = QtWidgets.QVBoxLayout(RollerDesign)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.SubtitleLabel = SubtitleLabel(RollerDesign)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(21)
        font.setBold(True)
        self.SubtitleLabel.setFont(font)
        self.SubtitleLabel.setObjectName("SubtitleLabel")
        self.verticalLayout.addWidget(self.SubtitleLabel, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.openButton = PrimaryPushButton(RollerDesign)
        self.openButton.setObjectName("openButton")
        self.horizontalLayout.addWidget(self.openButton)
        self.terminateButton = PrimaryPushButton(RollerDesign)
        self.terminateButton.setObjectName("terminateButton")
        self.horizontalLayout.addWidget(self.terminateButton)
        self.pathLineEdit = LineEdit(RollerDesign)
        self.pathLineEdit.setObjectName("pathLineEdit")
        self.horizontalLayout.addWidget(self.pathLineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)

        self.retranslateUi(RollerDesign)
        QtCore.QMetaObject.connectSlotsByName(RollerDesign)

    def retranslateUi(self, RollerDesign):
        _translate = QtCore.QCoreApplication.translate
        RollerDesign.setWindowTitle(_translate("RollerDesign", "Form"))
        self.SubtitleLabel.setText(_translate("RollerDesign", "打开exe程序"))
        self.openButton.setText(_translate("RollerDesign", "打开"))
        self.terminateButton.setText(_translate("RollerDesign", "终止"))
from qfluentwidgets import LineEdit, PrimaryPushButton, SubtitleLabel
