# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rollerDesign.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RollerDesign(object):
    def setupUi(self, RollerDesign):
        RollerDesign.setObjectName("RollerDesign")
        RollerDesign.resize(669, 386)
        self.verticalLayout = QtWidgets.QVBoxLayout(RollerDesign)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.SubtitleLabel = SubtitleLabel(RollerDesign)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(21)
        font.setBold(True)
        self.SubtitleLabel.setFont(font)
        self.SubtitleLabel.setObjectName("SubtitleLabel")
        self.verticalLayout.addWidget(self.SubtitleLabel, 0, QtCore.Qt.AlignHCenter)
        self.StrongBodyLabel = StrongBodyLabel(RollerDesign)
        self.StrongBodyLabel.setWordWrap(True)
        self.StrongBodyLabel.setObjectName("StrongBodyLabel")
        self.verticalLayout.addWidget(self.StrongBodyLabel)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.openButton = PrimaryPushButton(RollerDesign)
        self.openButton.setObjectName("openButton")
        self.horizontalLayout.addWidget(self.openButton)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)

        self.retranslateUi(RollerDesign)
        QtCore.QMetaObject.connectSlotsByName(RollerDesign)

    def retranslateUi(self, RollerDesign):
        _translate = QtCore.QCoreApplication.translate
        RollerDesign.setWindowTitle(_translate("RollerDesign", "Form"))
        self.SubtitleLabel.setText(_translate("RollerDesign", "打开exe程序"))
        self.StrongBodyLabel.setText(_translate("RollerDesign", "        闭环辊型设计程序运行速度与计算机硬件关系较大，执行时可能导致CPU占满，运行此程序会导致其他模块无法进行，另外此程序运行时间较长，使用128核心goldCPU运算时间为178小时。"))
        self.openButton.setText(_translate("RollerDesign", "打开闭环辊型设计程序"))
from qfluentwidgets import PrimaryPushButton, StrongBodyLabel, SubtitleLabel
