# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '板形控制能力评价Main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from .各轧机CVC辊形评价.CVC辊形评价 import CVCEvaluate
from .各轧机支持辊辊形评价.BUR辊形评价 import BUREvaluate
from .动态控制能力评价.动态控制能力评价 import DynamicControl


class Ui_FlatnessControlAbility(object):
    def setupUi(self, FlatnessControlAbility):
        FlatnessControlAbility.setObjectName("FlatnessControlAbility")
        FlatnessControlAbility.resize(1029, 754)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/板形分析.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        FlatnessControlAbility.setWindowIcon(icon)
        self.horizontalLayout = QtWidgets.QHBoxLayout(FlatnessControlAbility)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.NavigationBar = NavigationBar(FlatnessControlAbility)
        self.NavigationBar.setObjectName("NavigationBar")
        self.horizontalLayout.addWidget(self.NavigationBar)
        self.stackedWidget = QtWidgets.QStackedWidget(FlatnessControlAbility)
        self.stackedWidget.setObjectName("stackedWidget")
        self.preSetPage = QtWidgets.QWidget()
        self.preSetPage.setObjectName("preSetPage")
        self.stackedWidget.addWidget(self.preSetPage)
        self.dynamicControlPage = DynamicControl()
        self.dynamicControlPage.setObjectName("dynamicControlPage")
        self.stackedWidget.addWidget(self.dynamicControlPage)
        self.CVCPage = CVCEvaluate()
        self.CVCPage.setObjectName("CVCPage")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.CVCPage)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.stackedWidget.addWidget(self.CVCPage)
        self.BURPage = BUREvaluate()
        self.BURPage.setObjectName("BURPage")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.BURPage)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.stackedWidget.addWidget(self.BURPage)
        self.horizontalLayout.addWidget(self.stackedWidget)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 20)

        self.retranslateUi(FlatnessControlAbility)
        self.stackedWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(FlatnessControlAbility)

    def retranslateUi(self, FlatnessControlAbility):
        _translate = QtCore.QCoreApplication.translate
        FlatnessControlAbility.setWindowTitle(_translate("FlatnessControlAbility", "板形控制能力评价"))


from qfluentwidgets import NavigationBar
import resource_rc
