# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'abnormal_flatness_monitoring_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from abnormal_flatness_monitoring.PCA_monitor.PCA_GUI import MainWindow as PCA_GUI
from abnormal_flatness_monitoring.statistical_trace.statistical_GUI import MainWindow as statistical_GUI


class Ui_Monitor(object):
    def setupUi(self, Monitor):
        Monitor.setObjectName("Monitor")
        Monitor.resize(1201, 1068)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/跟踪.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Monitor.setWindowIcon(icon)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Monitor)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.NavigationBar = NavigationBar(Monitor)
        self.NavigationBar.setObjectName("NavigationBar")
        self.horizontalLayout.addWidget(self.NavigationBar)
        self.stackedWidget = QtWidgets.QStackedWidget(Monitor)
        self.stackedWidget.setObjectName("stackedWidget")
        self.PCAPage = PCA_GUI()
        self.PCAPage.setObjectName("PCAPage")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.PCAPage)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.stackedWidget.addWidget(self.PCAPage)
        self.statisticsPage = statistical_GUI()
        self.statisticsPage.setObjectName("statisticsPage")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.statisticsPage)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.stackedWidget.addWidget(self.statisticsPage)
        self.horizontalLayout.addWidget(self.stackedWidget)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 20)

        self.retranslateUi(Monitor)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Monitor)

    def retranslateUi(self, Monitor):
        _translate = QtCore.QCoreApplication.translate
        Monitor.setWindowTitle(_translate("Monitor", "异常板形监测溯源"))


from qfluentwidgets import NavigationBar
