# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'flatness_generate_data_model_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from flatness_generate_data_model.defect_exist_predict.板形缺陷有无预测 import MainWindowC2
from flatness_generate_data_model.defect_classify_predict.defect_classify_predict import MainWindowC
from flatness_generate_data_model.defect_regress_predict.defect_regress_predict import MainWindow


class Ui_板形生成数据建模(object):
    def setupUi(self, banxingshengchengshuju):
        banxingshengchengshuju.setObjectName("banxingshengchengshuju")
        banxingshengchengshuju.resize(1200, 900)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/板形生成数据建模.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        banxingshengchengshuju.setWindowIcon(icon)
        self.horizontalLayout = QtWidgets.QHBoxLayout(banxingshengchengshuju)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.NavigationBar = NavigationBar(banxingshengchengshuju)
        self.NavigationBar.setObjectName("NavigationBar")
        self.horizontalLayout.addWidget(self.NavigationBar)
        self.stackedWidget = QtWidgets.QStackedWidget(banxingshengchengshuju)
        self.stackedWidget.setObjectName("stackedWidget")
        self.existPage = MainWindowC2()
        # self.existPage = QtWidgets.QWidget()
        self.existPage.setObjectName("existPage")
        self.stackedWidget.addWidget(self.existPage)
        self.classificationPage = MainWindowC()
        # self.classificationPage = QtWidgets.QWidget()
        self.classificationPage.setObjectName("classificationPage")
        self.stackedWidget.addWidget(self.classificationPage)
        self.regressionPage = MainWindow()
        # self.regressionPage = QtWidgets.QWidget()
        self.regressionPage.setObjectName("regressionPage")
        self.stackedWidget.addWidget(self.regressionPage)
        self.horizontalLayout.addWidget(self.stackedWidget)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 20)

        self.retranslateUi(banxingshengchengshuju)
        QtCore.QMetaObject.connectSlotsByName(banxingshengchengshuju)

    def retranslateUi(self, banxingshengchengshuju):
        _translate = QtCore.QCoreApplication.translate
        banxingshengchengshuju.setWindowTitle(_translate("banxingshengchengshuju", "板形生成数据建模"))
from qfluentwidgets import NavigationBar
