# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '表格自学习.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Instruction(object):
    def setupUi(self, Instruction):
        Instruction.setObjectName("Instruction")
        Instruction.resize(1253, 899)
        self.gridLayout = QtWidgets.QGridLayout(Instruction)
        self.gridLayout.setObjectName("gridLayout")
        self.TitleLabel = TitleLabel(Instruction)
        self.TitleLabel.setObjectName("TitleLabel")
        self.gridLayout.addWidget(self.TitleLabel, 0, 0, 1, 1)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.CardWidget = CardWidget(Instruction)
        self.CardWidget.setObjectName("CardWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.CardWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.SubtitleLabel = SubtitleLabel(self.CardWidget)
        self.SubtitleLabel.setObjectName("SubtitleLabel")
        self.verticalLayout.addWidget(self.SubtitleLabel)
        self.BodyLabel = BodyLabel(self.CardWidget)
        self.BodyLabel.setStyleSheet("font: 25 10pt \"宋体\";")
        self.BodyLabel.setWordWrap(True)
        self.BodyLabel.setObjectName("BodyLabel")
        self.verticalLayout.addWidget(self.BodyLabel)
        self.label = QtWidgets.QLabel(self.CardWidget)
        self.label.setStyleSheet("image: url(:/images/doc/assets/image-20230711100555310.png);")
        self.label.setText("")
        self.label.setScaledContents(False)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.verticalLayout.setStretch(2, 5)
        self.verticalLayout_6.addWidget(self.CardWidget)
        self.CardWidget_2 = CardWidget(Instruction)
        self.CardWidget_2.setObjectName("CardWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.CardWidget_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.SubtitleLabel_2 = SubtitleLabel(self.CardWidget_2)
        self.SubtitleLabel_2.setStyleSheet("font: 15pt \"黑体\";")
        self.SubtitleLabel_2.setObjectName("SubtitleLabel_2")
        self.verticalLayout_2.addWidget(self.SubtitleLabel_2)
        self.BodyLabel_2 = BodyLabel(self.CardWidget_2)
        self.BodyLabel_2.setStyleSheet("font: 10pt \"宋体\";")
        self.BodyLabel_2.setWordWrap(True)
        self.BodyLabel_2.setObjectName("BodyLabel_2")
        self.verticalLayout_2.addWidget(self.BodyLabel_2)
        self.label_2 = QtWidgets.QLabel(self.CardWidget_2)
        self.label_2.setStyleSheet("image: url(:/images/doc/assets/image-20230711100659251.png);")
        self.label_2.setText("")
        self.label_2.setScaledContents(False)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 1)
        self.verticalLayout_2.setStretch(2, 5)
        self.verticalLayout_6.addWidget(self.CardWidget_2)
        self.gridLayout.addLayout(self.verticalLayout_6, 1, 0, 1, 1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.CardWidget_3 = CardWidget(Instruction)
        self.CardWidget_3.setObjectName("CardWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.CardWidget_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.SubtitleLabel_3 = SubtitleLabel(self.CardWidget_3)
        self.SubtitleLabel_3.setObjectName("SubtitleLabel_3")
        self.verticalLayout_3.addWidget(self.SubtitleLabel_3)
        self.BodyLabel_3 = BodyLabel(self.CardWidget_3)
        self.BodyLabel_3.setWordWrap(True)
        self.BodyLabel_3.setObjectName("BodyLabel_3")
        self.verticalLayout_3.addWidget(self.BodyLabel_3)
        self.label_3 = QtWidgets.QLabel(self.CardWidget_3)
        self.label_3.setStyleSheet("image: url(:/images/doc/assets/image-20230711100958555.png);")
        self.label_3.setText("")
        self.label_3.setScaledContents(False)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.verticalLayout_3.setStretch(0, 1)
        self.verticalLayout_3.setStretch(1, 1)
        self.verticalLayout_3.setStretch(2, 5)
        self.verticalLayout_5.addWidget(self.CardWidget_3)
        self.CardWidget_4 = CardWidget(Instruction)
        self.CardWidget_4.setObjectName("CardWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.CardWidget_4)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.SubtitleLabel_4 = SubtitleLabel(self.CardWidget_4)
        self.SubtitleLabel_4.setObjectName("SubtitleLabel_4")
        self.verticalLayout_4.addWidget(self.SubtitleLabel_4)
        self.BodyLabel_4 = BodyLabel(self.CardWidget_4)
        self.BodyLabel_4.setWordWrap(True)
        self.BodyLabel_4.setObjectName("BodyLabel_4")
        self.verticalLayout_4.addWidget(self.BodyLabel_4)
        self.label_4 = QtWidgets.QLabel(self.CardWidget_4)
        self.label_4.setStyleSheet("image: url(:/images/doc/assets/image-20230731192829016.png);")
        self.label_4.setText("")
        self.label_4.setScaledContents(False)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.verticalLayout_4.setStretch(0, 1)
        self.verticalLayout_4.setStretch(1, 1)
        self.verticalLayout_4.setStretch(2, 5)
        self.verticalLayout_5.addWidget(self.CardWidget_4)
        self.gridLayout.addLayout(self.verticalLayout_5, 1, 1, 1, 1)

        self.retranslateUi(Instruction)
        QtCore.QMetaObject.connectSlotsByName(Instruction)

    def retranslateUi(self, Instruction):
        _translate = QtCore.QCoreApplication.translate
        Instruction.setWindowTitle(_translate("Instruction", "Form"))
        self.TitleLabel.setText(_translate("Instruction", "此界面为单独的exe程序"))
        self.SubtitleLabel.setText(_translate("Instruction", "主界面"))
        self.BodyLabel.setText(
            _translate("Instruction", "选择初值表的保存路径、预设定表格的保存路径，指定上一次更新的`id`，点击`run`"))
        self.SubtitleLabel_2.setText(_translate("Instruction", "菜单栏"))
        self.BodyLabel_2.setText(
            _translate("Instruction", "Setting：设置数据库（database）和预设定更新（preset）的相关参数"))
        self.SubtitleLabel_3.setText(_translate("Instruction", "preset的设置界面"))
        self.BodyLabel_3.setText(_translate("Instruction", "遗忘因子: 预设定在线更新对历史样本的取舍策略\n"
                                                           "ISR_limit: 中间辊窜辊限值\n"
                                                           "初值更新时间: 每天5:00自动执行程序"))
        self.SubtitleLabel_4.setText(_translate("Instruction", "Database的设置界面"))
        self.BodyLabel_4.setText(_translate("Instruction", "host:      数据库地址\n"
                                                           "port:      数据库端口号\n"
                                                           "user:       用户\n"
                                                           "passward:   密码\n"
                                                           "database:   数据库名称\n"
                                                           "multi-size: 指定进程数, 快速处理文件"))


from qfluentwidgets import BodyLabel, CardWidget, SubtitleLabel, TitleLabel
from 板形控制数模优化.表格自学习 import res_rc
