# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '登录界面.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginWindow(object):
    def setupUi(self, LoginWindow):
        LoginWindow.setObjectName("LoginWindow")
        LoginWindow.resize(800, 450)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/img/首钢.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        LoginWindow.setWindowIcon(icon)
        self.widget = QtWidgets.QWidget(LoginWindow)
        self.widget.setGeometry(QtCore.QRect(0, 0, 800, 450))
        self.widget.setStyleSheet("QPushButton#login_pushButton {\n"
"    background-color: qlineargradient(spread: pad, x1: 0, y1: 0.505682, x2: 1, y2: 0.477, stop: 0 rgba(11, 131, 120, 219), stop: 1 rgba(85, 98, 112, 226));\n"
"    color: rgba(255, 255, 255, 210);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton#login_pushButton:hover {\n"
"    background-color: qlineargradient(spread: pad, x1: 0, y1: 0.505682, x2: 1, y2: 0.477, stop: 0 rgba(150, 123, 1111, 219), stop: 1 rgba(85, 81, 84, 226));\n"
"}\n"
"\n"
"QPushButton#entry_pushButton {\n"
"border: none; /* 这里设置了无边框 */\n"
"}\n"
"\n"
"\n"
"QPushButton#login_pushButton:pressed {\n"
"    padding-left: 5px;\n"
"    padding-top: 5px;\n"
"    background-color: rgba(150, 123, 111, 255);\n"
"}\n"
"\n"
"QPushButton#forget_password_pushButton,\n"
"QPushButton#register_pushButton,\n"
"QPushButton#mysql_pushButton {\n"
"    background-color: rgba(0, 0, 0, 0);\n"
"    border: none;\n"
"    border-bottom: 1px solid rgb(179, 179, 179);\n"
"    color: rgba(0, 0, 0, 240);\n"
"}\n"
"\n"
"QPushButton#github_pushButton,\n"
"QPushButton#phone_pushButton,\n"
"QPushButton#email_pushButton {\n"
"    background-color: rgba(0, 0, 0, 0);\n"
"    color: rgba(85, 98, 112, 255);\n"
"}\n"
"\n"
"QPushButton#github_pushButton:hover,\n"
"QPushButton#phone_pushButton:hover,\n"
"QPushButton#email_pushButton:hover {\n"
"    color: rgba(131, 96, 53, 255);\n"
"}\n"
"\n"
"QPushButton#github_pushButton:pressed,\n"
"QPushButton#phone_pushButton:pressed,\n"
"QPushButton#email_pushButton:pressed {\n"
"    padding-left: 5px;\n"
"    padding-top: 5px;\n"
"    color: rgba(91, 88, 53, 255);\n"
"}\n"
"\n"
"QPushButton#close_pushButton{\n"
" background-color: #ce5137;\n"
" border-radius:10px;\n"
"}\n"
"\n"
"QPushButton#close_pushButton:hover{\n"
" background-size: cover;\n"
" background-image: url(:/icons/icons/close.svg);\n"
"}\n"
"\n"
"QPushButton#min_pushButton{\n"
" background-color: #a1c661;\n"
" border-radius:10px;\n"
"}\n"
"\n"
"QPushButton#min_pushButton:hover{\n"
" background-size: cover;\n"
" background-image: url(:/icons/icons/minimize.svg);\n"
"}\n"
"\n"
"")
        self.widget.setObjectName("widget")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setGeometry(QtCore.QRect(590, 60, 180, 40))
        self.label_5.setMinimumSize(QtCore.QSize(180, 40))
        self.label_5.setMaximumSize(QtCore.QSize(180, 40))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_5.setStyleSheet("color:rgba(0,0,0,200);")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.login_pushButton = QtWidgets.QPushButton(self.widget)
        self.login_pushButton.setGeometry(QtCore.QRect(585, 260, 190, 40))
        self.login_pushButton.setMinimumSize(QtCore.QSize(190, 40))
        self.login_pushButton.setMaximumSize(QtCore.QSize(190, 40))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.login_pushButton.setFont(font)
        self.login_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.login_pushButton.setObjectName("login_pushButton")
        self.github_pushButton = QtWidgets.QPushButton(self.widget)
        self.github_pushButton.setGeometry(QtCore.QRect(610, 351, 30, 30))
        self.github_pushButton.setMinimumSize(QtCore.QSize(30, 30))
        self.github_pushButton.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setFamily("Social Media Circled")
        font.setPointSize(15)
        self.github_pushButton.setFont(font)
        self.github_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.github_pushButton.setStyleSheet("")
        self.github_pushButton.setObjectName("github_pushButton")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(560, 10, 240, 431))
        self.label_4.setStyleSheet("background-color:rgba(255,255,255,255);\n"
"")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.close_pushButton = QtWidgets.QPushButton(self.widget)
        self.close_pushButton.setGeometry(QtCore.QRect(770, 20, 20, 20))
        self.close_pushButton.setMinimumSize(QtCore.QSize(20, 20))
        self.close_pushButton.setMaximumSize(QtCore.QSize(20, 20))
        self.close_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.close_pushButton.setStyleSheet("")
        self.close_pushButton.setText("")
        self.close_pushButton.setObjectName("close_pushButton")
        self.password_lineEdit = QtWidgets.QLineEdit(self.widget)
        self.password_lineEdit.setGeometry(QtCore.QRect(585, 195, 190, 40))
        self.password_lineEdit.setMinimumSize(QtCore.QSize(190, 40))
        self.password_lineEdit.setMaximumSize(QtCore.QSize(190, 40))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(15)
        self.password_lineEdit.setFont(font)
        self.password_lineEdit.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46,82,101,200);\n"
"color:rgba(0,0,0,240);\n"
"padding-bottom:7px;")
        self.password_lineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_lineEdit.setObjectName("password_lineEdit")
        self.entry_pushButton = QtWidgets.QPushButton(self.widget)
        self.entry_pushButton.setGeometry(QtCore.QRect(10, 420, 75, 23))
        self.entry_pushButton.setMinimumSize(QtCore.QSize(75, 23))
        self.entry_pushButton.setMaximumSize(QtCore.QSize(75, 23))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.entry_pushButton.setFont(font)
        self.entry_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.entry_pushButton.setObjectName("entry_pushButton")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(40, 10, 521, 431))
        self.label.setStyleSheet("image: url(:/images/img/combination.jpg);\n"
"background-color: rgb(255, 255, 255);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(620, 410, 171, 31))
        self.label_2.setStyleSheet("font: 10pt \"Consolas\";")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.forget_password_pushButton = QtWidgets.QPushButton(self.widget)
        self.forget_password_pushButton.setGeometry(QtCore.QRect(600, 310, 75, 23))
        self.forget_password_pushButton.setMinimumSize(QtCore.QSize(75, 23))
        self.forget_password_pushButton.setMaximumSize(QtCore.QSize(75, 23))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.forget_password_pushButton.setFont(font)
        self.forget_password_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.forget_password_pushButton.setObjectName("forget_password_pushButton")
        self.user_name_lineEdit = QtWidgets.QLineEdit(self.widget)
        self.user_name_lineEdit.setGeometry(QtCore.QRect(585, 130, 190, 40))
        self.user_name_lineEdit.setMinimumSize(QtCore.QSize(190, 40))
        self.user_name_lineEdit.setMaximumSize(QtCore.QSize(190, 40))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(15)
        self.user_name_lineEdit.setFont(font)
        self.user_name_lineEdit.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46,82,101,200);\n"
"color:rgba(0,0,0,240);\n"
"padding-bottom:7px;")
        self.user_name_lineEdit.setObjectName("user_name_lineEdit")
        self.register_pushButton = QtWidgets.QPushButton(self.widget)
        self.register_pushButton.setGeometry(QtCore.QRect(690, 310, 75, 23))
        self.register_pushButton.setMinimumSize(QtCore.QSize(75, 23))
        self.register_pushButton.setMaximumSize(QtCore.QSize(75, 23))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(12)
        self.register_pushButton.setFont(font)
        self.register_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.register_pushButton.setObjectName("register_pushButton")
        self.mysql_pushButton = QtWidgets.QPushButton(self.widget)
        self.mysql_pushButton.setGeometry(QtCore.QRect(570, 20, 75, 23))
        self.mysql_pushButton.setMinimumSize(QtCore.QSize(75, 23))
        self.mysql_pushButton.setMaximumSize(QtCore.QSize(75, 23))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(13)
        self.mysql_pushButton.setFont(font)
        self.mysql_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.mysql_pushButton.setObjectName("mysql_pushButton")
        self.phone_pushButton = QtWidgets.QPushButton(self.widget)
        self.phone_pushButton.setGeometry(QtCore.QRect(659, 351, 30, 30))
        self.phone_pushButton.setMinimumSize(QtCore.QSize(30, 30))
        self.phone_pushButton.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setFamily("Social Media Circled")
        font.setPointSize(15)
        self.phone_pushButton.setFont(font)
        self.phone_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.phone_pushButton.setStyleSheet("")
        self.phone_pushButton.setObjectName("phone_pushButton")
        self.min_pushButton = QtWidgets.QPushButton(self.widget)
        self.min_pushButton.setGeometry(QtCore.QRect(750, 20, 20, 20))
        self.min_pushButton.setMinimumSize(QtCore.QSize(20, 20))
        self.min_pushButton.setMaximumSize(QtCore.QSize(20, 20))
        self.min_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.min_pushButton.setStyleSheet("")
        self.min_pushButton.setText("")
        self.min_pushButton.setObjectName("min_pushButton")
        self.email_pushButton = QtWidgets.QPushButton(self.widget)
        self.email_pushButton.setGeometry(QtCore.QRect(708, 351, 30, 30))
        self.email_pushButton.setMinimumSize(QtCore.QSize(30, 30))
        self.email_pushButton.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setFamily("Social Media Circled")
        font.setPointSize(15)
        self.email_pushButton.setFont(font)
        self.email_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.email_pushButton.setStyleSheet("")
        self.email_pushButton.setObjectName("email_pushButton")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(0, 10, 81, 431))
        self.label_3.setStyleSheet("border-top-left-radius:50px;\n"
"background-color: rgb(255, 255, 255);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_3.raise_()
        self.label_4.raise_()
        self.close_pushButton.raise_()
        self.password_lineEdit.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.forget_password_pushButton.raise_()
        self.user_name_lineEdit.raise_()
        self.register_pushButton.raise_()
        self.mysql_pushButton.raise_()
        self.phone_pushButton.raise_()
        self.min_pushButton.raise_()
        self.email_pushButton.raise_()
        self.github_pushButton.raise_()
        self.login_pushButton.raise_()
        self.label_5.raise_()
        self.entry_pushButton.raise_()

        self.retranslateUi(LoginWindow)
        QtCore.QMetaObject.connectSlotsByName(LoginWindow)

    def retranslateUi(self, LoginWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginWindow.setWindowTitle(_translate("LoginWindow", "登录界面"))
        self.label_5.setText(_translate("LoginWindow", "登录界面"))
        self.login_pushButton.setText(_translate("LoginWindow", "登录"))

        self.password_lineEdit.setPlaceholderText(_translate("LoginWindow", "密码"))
        self.entry_pushButton.setText(_translate("LoginWindow", "直接进入"))
        self.label_2.setText(_translate("LoginWindow", "designed by MeZhou group"))
        self.forget_password_pushButton.setText(_translate("LoginWindow", "忘记密码？"))
        self.user_name_lineEdit.setPlaceholderText(_translate("LoginWindow", "用户名"))
        self.register_pushButton.setText(_translate("LoginWindow", "用户注册"))
        self.mysql_pushButton.setText(_translate("LoginWindow", "数据库"))


from 登录及主界面.res import icons_rc
