# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'concentration_IU_scatter.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AvgIUAndLiquid(object):
    def setupUi(self, AvgIUAndLiquid):
        AvgIUAndLiquid.setObjectName("AvgIUAndLiquid")
        AvgIUAndLiquid.resize(1771, 978)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/预览.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        AvgIUAndLiquid.setWindowIcon(icon)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(AvgIUAndLiquid)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.CardWidget = CardWidget(AvgIUAndLiquid)
        self.CardWidget.setObjectName("CardWidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.CardWidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.RadioButton2021 = RadioButton(self.CardWidget)
        self.RadioButton2021.setObjectName("RadioButton2021")
        self.horizontalLayout_2.addWidget(self.RadioButton2021)
        self.RadioButton2022 = RadioButton(self.CardWidget)
        self.RadioButton2022.setObjectName("RadioButton2022")
        self.horizontalLayout_2.addWidget(self.RadioButton2022)
        self.RadioButton2023 = RadioButton(self.CardWidget)
        self.RadioButton2023.setCheckable(True)
        self.RadioButton2023.setChecked(False)
        self.RadioButton2023.setObjectName("RadioButton2023")
        self.horizontalLayout_2.addWidget(self.RadioButton2023)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.gridLayoutLeft = QtWidgets.QGridLayout()
        self.gridLayoutLeft.setObjectName("gridLayoutLeft")
        self.widget = QtWidgets.QWidget(self.CardWidget)
        self.widget.setObjectName("widget")
        self.gridLayoutLeft.addWidget(self.widget, 0, 0, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayoutLeft)
        self.verticalLayout_4.setStretch(0, 1)
        self.verticalLayout_4.setStretch(1, 20)
        self.horizontalLayout_3.addWidget(self.CardWidget)
        self.horizontalLayout_3.setStretch(0, 1)

        self.retranslateUi(AvgIUAndLiquid)
        QtCore.QMetaObject.connectSlotsByName(AvgIUAndLiquid)

    def retranslateUi(self, AvgIUAndLiquid):
        _translate = QtCore.QCoreApplication.translate
        AvgIUAndLiquid.setWindowTitle(_translate("AvgIUAndLiquid", "全年浓度与IU均值散点"))
        self.RadioButton2021.setText(_translate("AvgIUAndLiquid", "2021"))
        self.RadioButton2022.setText(_translate("AvgIUAndLiquid", "2022"))
        self.RadioButton2023.setText(_translate("AvgIUAndLiquid", "2023"))


from qfluentwidgets import CardWidget, RadioButton
