# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'terminal.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MyTerminal(object):
    def setupUi(self, MyTerminal):
        MyTerminal.setObjectName("MyTerminal")
        MyTerminal.resize(823, 535)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/终端.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MyTerminal.setWindowIcon(icon)
        self.horizontalLayout = QtWidgets.QHBoxLayout(MyTerminal)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.terminal = QtWidgets.QPlainTextEdit(MyTerminal)
        self.terminal.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"border: 1px solid rgba(0, 0, 0, 13);\n"
"border-bottom: 1px solid rgba(0, 0, 0, 100);\n"
"border-radius: 5px;\n"
"/* font: 14px \"Segoe UI\", \"Microsoft YaHei\"; */\n"
"padding: 0px 10px;\n"
"selection-background-color: #00a7b3;\n"
"font: 12pt \"Adobe Heiti Std\";")
        self.terminal.setReadOnly(True)
        self.terminal.setObjectName("terminal")
        self.horizontalLayout.addWidget(self.terminal)

        self.retranslateUi(MyTerminal)
        QtCore.QMetaObject.connectSlotsByName(MyTerminal)

    def retranslateUi(self, MyTerminal):
        _translate = QtCore.QCoreApplication.translate
        MyTerminal.setWindowTitle(_translate("MyTerminal", "MyTerminal"))
        self.terminal.setPlaceholderText(_translate("MyTerminal", "Console"))
import resource_rc
