# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'feedback_control_strategy_simulation_analysis.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from flatness_control_data_model_optimization.feedback_control_strategy_simulation_analysis.single_strategy.single_strategy import 单策略对比
from flatness_control_data_model_optimization.feedback_control_strategy_simulation_analysis.multiple_strategy.multiple_strategy import 多策略对比


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(890, 662)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.pivot = SegmentedWidget(Form)
        self.pivot.setObjectName("pivot")
        self.gridLayout.addWidget(self.pivot, 0, 0, 1, 1)
        self.stackedWidget = QtWidgets.QStackedWidget(Form)
        self.stackedWidget.setObjectName("stackedWidget")
        self.singlePolicySubPage = 单策略对比()
        # self.singlePolicySubPage = QtWidgets.QWidget()
        self.singlePolicySubPage.setObjectName("singlePolicySubPage")
        self.stackedWidget.addWidget(self.singlePolicySubPage)
        self.multiPolicySubPage = 多策略对比()
        # self.multiPolicySubPage = QtWidgets.QWidget()
        self.multiPolicySubPage.setObjectName("multiPolicySubPage")
        self.stackedWidget.addWidget(self.multiPolicySubPage)
        self.gridLayout.addWidget(self.stackedWidget, 1, 0, 1, 2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "反馈控制策略"))


from qfluentwidgets import SegmentedWidget
