# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '停机查询界面new.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_StopRollSearch(object):
    def setupUi(self, StopRollSearch):
        StopRollSearch.setObjectName("StopRollSearch")
        StopRollSearch.resize(1000, 800)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/查询.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        StopRollSearch.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(StopRollSearch)
        self.gridLayout.setObjectName("gridLayout")
        self.LeftWidget = CardWidget(StopRollSearch)
        self.LeftWidget.setObjectName("LeftWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.LeftWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.SubtitleLabel = SubtitleLabel(self.LeftWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SubtitleLabel.sizePolicy().hasHeightForWidth())
        self.SubtitleLabel.setSizePolicy(sizePolicy)
        self.SubtitleLabel.setMaximumSize(QtCore.QSize(16777215, 50))
        self.SubtitleLabel.setObjectName("SubtitleLabel")
        self.verticalLayout.addWidget(self.SubtitleLabel)
        self.CalendarPicker = CalendarPicker(self.LeftWidget)
        self.CalendarPicker.setObjectName("CalendarPicker")
        self.verticalLayout.addWidget(self.CalendarPicker)
        self.TableWidget = TableWidget(self.LeftWidget)
        self.TableWidget.setObjectName("TableWidget")
        self.TableWidget.setColumnCount(0)
        self.TableWidget.setRowCount(0)
        self.verticalLayout.addWidget(self.TableWidget)
        self.gridLayout.addWidget(self.LeftWidget, 0, 0, 2, 1)
        self.RightUpWidget = CardWidget(StopRollSearch)
        self.RightUpWidget.setObjectName("RightUpWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.RightUpWidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.SubtitleLabel_2 = SubtitleLabel(self.RightUpWidget)
        self.SubtitleLabel_2.setObjectName("SubtitleLabel_2")
        self.verticalLayout_3.addWidget(self.SubtitleLabel_2)
        self.TableWidget_2 = TableWidget(self.RightUpWidget)
        self.TableWidget_2.setObjectName("TableWidget_2")
        self.TableWidget_2.setColumnCount(0)
        self.TableWidget_2.setRowCount(0)
        self.verticalLayout_3.addWidget(self.TableWidget_2)
        self.gridLayout.addWidget(self.RightUpWidget, 0, 1, 1, 1)
        self.RightDownWidget = CardWidget(StopRollSearch)
        self.RightDownWidget.setObjectName("RightDownWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.RightDownWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.SubtitleLabel_3 = SubtitleLabel(self.RightDownWidget)
        self.SubtitleLabel_3.setObjectName("SubtitleLabel_3")
        self.verticalLayout_2.addWidget(self.SubtitleLabel_3)
        self.TableWidget_3 = TableWidget(self.RightDownWidget)
        self.TableWidget_3.setObjectName("TableWidget_3")
        self.TableWidget_3.setColumnCount(0)
        self.TableWidget_3.setRowCount(0)
        self.verticalLayout_2.addWidget(self.TableWidget_3)
        self.gridLayout.addWidget(self.RightDownWidget, 1, 1, 1, 1)

        self.retranslateUi(StopRollSearch)
        QtCore.QMetaObject.connectSlotsByName(StopRollSearch)

    def retranslateUi(self, StopRollSearch):
        _translate = QtCore.QCoreApplication.translate
        StopRollSearch.setWindowTitle(_translate("StopRollSearch", "Form"))
        self.SubtitleLabel.setText(_translate("StopRollSearch", "选择日期"))
        self.SubtitleLabel_2.setText(_translate("StopRollSearch", "停机前钢卷信息"))
        self.SubtitleLabel_3.setText(_translate("StopRollSearch", "停机后钢卷信息"))
from qfluentwidgets import CalendarPicker, CardWidget, SubtitleLabel, TableWidget
import resource_rc
