# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '板形生成数据建模Main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from .板形缺陷模式有无预测.板形缺陷有无预测 import MainWindowC2
from .板形缺陷多分类预测.板形缺陷模式多分类预测 import MainWindowC
from .板形缺陷定量回归预测.板形缺陷定量回归预测 import mainWindow


class Ui_板形生成数据建模(object):
    def setupUi(self, banxingshengchengshuju):
        banxingshengchengshuju.setObjectName("banxingshengchengshuju")
        banxingshengchengshuju.resize(864, 611)
        self.horizontalLayout = QtWidgets.QHBoxLayout(banxingshengchengshuju)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.NavigationBar = NavigationBar(banxingshengchengshuju)
        self.NavigationBar.setObjectName("NavigationBar")
        self.horizontalLayout.addWidget(self.NavigationBar)
        self.stackedWidget = QtWidgets.QStackedWidget(banxingshengchengshuju)
        self.stackedWidget.setObjectName("stackedWidget")
        self.existPage = MainWindowC2()
        self.existPage.setObjectName("existPage")
        self.stackedWidget.addWidget(self.existPage)
        self.classificationPage = MainWindowC()
        self.classificationPage.setObjectName("classificationPage")
        self.stackedWidget.addWidget(self.classificationPage)
        self.regressionPage = mainWindow()
        self.regressionPage.setObjectName("regressionPage")
        self.stackedWidget.addWidget(self.regressionPage)
        self.horizontalLayout.addWidget(self.stackedWidget)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 20)

        self.retranslateUi(banxingshengchengshuju)
        QtCore.QMetaObject.connectSlotsByName(banxingshengchengshuju)

    def retranslateUi(self, banxingshengchengshuju):
        _translate = QtCore.QCoreApplication.translate
        banxingshengchengshuju.setWindowTitle(_translate("banxingshengchengshuju", "Form"))
from qfluentwidgets import NavigationBar
