# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\programdata\pycharm\首钢报告\GUI\wsk_work\轧辊服役期2022\flatness.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frame_4(object):
    def setupUi(self, Frame_4):
        Frame_4.setObjectName("Frame_4")
        Frame_4.resize(1022, 674)
        Frame_4.setMinimumSize(QtCore.QSize(1022, 674))
        Frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        Frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.gridLayout = QtWidgets.QGridLayout(Frame_4)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.gridLayout.addLayout(self.verticalLayout, 1, 0, 1, 1)
        self.textEdit_2 = QtWidgets.QTextEdit(Frame_4)
        self.textEdit_2.setObjectName("textEdit_2")
        self.gridLayout.addWidget(self.textEdit_2, 0, 0, 1, 1)

        self.retranslateUi(Frame_4)
        QtCore.QMetaObject.connectSlotsByName(Frame_4)

    def retranslateUi(self, Frame_4):
        _translate = QtCore.QCoreApplication.translate
        Frame_4.setWindowTitle(_translate("Frame_4", "带钢iu曲线"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Frame_4 = QtWidgets.QFrame()
    ui = Ui_Frame_4()
    ui.setupUi(Frame_4)
    Frame_4.show()
    sys.exit(app.exec_())
